name: status_saver
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.4
  share_plus: ^10.1.4
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  flutter_svg: ^2.0.17
  photo_view: ^0.14.0
  video_player: ^2.8.3
  get_thumbnail_video: ^0.7.3
  url_launcher: ^6.2.5
  package_info_plus: ^8.0.0
  saf_stream: ^0.11.2
  saf_util: ^0.7.0
  shared_preferences: ^2.5.3
  share_whatsapp:
    path: plugins/share_whatsapp

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
